data = r"C:\Users\KernelGM\Desktop\teste-xcelis\solution\dados"
logs = r"C:\Users\KernelGM\Desktop\teste-xcelis\solution\logs"
demands = r"C:\Users\KernelGM\Desktop\teste-xcelis\solution\dados\pedidos"
output = r"C:\Users\KernelGM\Desktop\teste-xcelis\solution\output"
output_demands = r"C:\Users\KernelGM\Desktop\teste-xcelis\solution\output\demands"
